FROM node:14-alpine

WORKDIR /app

# add '/app/node_modules/.bin' to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# install application dependencies
COPY package*.json ./
RUN npm install
# RUN npm install react-scripts -g

# copy app files
COPY . .

EXPOSE 3000
CMD ["npm", "start"]

# FROM node:alpine as build

# WORKDIR /usr/app

# COPY package*.json ./
# RUN yarn

# COPY . .

# CMD ["yarn", "build"]
# # FROM node:13-alpine as build
# # WORKDIR /app

# # ENV PATH /app/node_modules/.bin:$PATH
# # COPY package.json /app/package.json
# # RUN yarn

# COPY . /app
#RUN yarn build
# # production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD [“nginx”, “-g”, “daemon off;”]

