version: '3.7'
services:
  app-prod:
    container_name: macon-dashboard-app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '3000:3000'
    volumes:
      - "/usr/srs/app/node_modules"
      - "./:/usr/srs/app"
